rules:
- id: github-action-push-without-branches
  message: The 'branches' field contains no branches for push configuration.
  severity: ERROR
  languages:
  - yaml
  patterns:
  - pattern: |
      ...
      jobs:
        ...
        $NAME:
          ...
          steps:
            ...
            - uses: returntocorp/semgrep-action@v1
              ...
            ...
          ...
        ...
      ...
  metadata:
    category: correctness
    technology:
    - github-action
