rules:
- fix: distributed.security.Security(..., require_encryption=True, ...)
  id: require-encryption
  languages:
  - python
  message: Initializing the a security context for Dask (`distributed`) without "require_encription"
    keyword argument may silently fail to provide security. See https://distributed.dask.org/en/latest/tls.html?highlight=require_encryption#parameters
  metadata:
    category: security
    cwe: "CWE-16: Configuration"
    technology:
    - distributed
  patterns:
  - pattern-not: |
      distributed.security.Security(..., require_encryption=True, ...)
  - pattern: |
      distributed.security.Security(...)
  severity: WARNING
