rules:
  - id: require-encryption
    patterns:
      - pattern: |
          distributed.security.Security(..., require_encryption=$VAL, ...)
      - metavariable-pattern:
          metavariable: $VAL
          pattern: |
            False
      - focus-metavariable: $VAL
    fix: |
      True
    message: >-
      Initializing the a security context for Dask (`distributed`) without "require_encription" keyword argument may silently fail to provide security. See https://distributed.dask.org/en/latest/tls.html?highlight=require_encryption#parameters
    severity: WARNING
    metadata:
      category: security
      technology:
        - distributed
    languages:
      - python
