rules:
- id: unsafe-argon2-config
  mode: taint
  pattern-sources:
    - patterns:
      - pattern-inside: |
          $ARGON = require('argon2');
          ...
      - pattern: |
          {type: ...}
  pattern-sanitizers:
    - patterns:
      - pattern: |
          {type: $ARGON.argon2id}
          ...
  pattern-sinks:
      - patterns:
        - pattern: |
            $ARGON.hash(...)
  metadata:
    references:
    - https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
    category: security
    technology:
    - argon2
    - cryptography
  message: |
    Use argon2id for password hashing.
  severity: WARNING
  languages:
  - javascript
  - typescript
