rules:
- id: unsafe-argon2-config
  mode: taint
  pattern-sources:
    - patterns:
      - pattern-inside: |
          $ARGON = require('argon2');
          ...
      - pattern: |
          {type: ...}
  pattern-sanitizers:
    - patterns:
      - pattern: |
          {type: $ARGON.argon2id}
          ...
  pattern-sinks:
      - patterns:
        - pattern: |
            $Y
        - pattern-inside: |
            $ARGON.hash(...,$Y)
  metadata:
    references:
    - https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html
    - https://eprint.iacr.org/2016/759.pdf
    - https://www.cs.tau.ac.il/~tromer/papers/cache-joc-20090619.pdf
    category: security
    technology:
    - argon2
    - cryptography
  message: >-
    Prefer Argon2id where possible. Argon2d is designed to resist GPU-based attacks but introduces cache-based side-channel attacks while Argon2i has a published attack (Alwen-Blocki) that necessitate >10 memory passes.
    Argon2id is a hybrid approach using both Argon2d and Argon2i to mitigate the weaknesses of each individual scheme.
  severity: WARNING
  languages:
  - javascript
  - typescript
