apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: bad-role
rules:
  # ok: cluster-role-with-all-access
  - apiGroups:
      - apps
    resources:
      - "*"
    verbs:
      - "*"
  # ruleid: cluster-role-with-all-access
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"
  # ok: cluster-role-with-all-access
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - list
  # ok: cluster-role-with-all-access
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  # ruleid: cluster-role-with-all-access
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
      - customresourcedefinitions/status
    verbs:
      - "*"
