name: Increase semgrep version for historical test 
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  increase-historical-semgrep-version:
    name: increase-historical-semgrep-version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Increase version
      working-directory: .github/workflows
      shell: bash
      run: |
        FILENAME="semgrep-rules-test-historical.yml"
        SEMGREP_VERSION=`grep -ow "0.[0-9][0-9].0" $FILENAME | head -1`
        SEMGREP_VERSION_SHORT=${SEMGREP_VERSION:2:2}
        INCREASED_SEMGREP_VERSION="0.$(($SEMGREP_VERSION_SHORT + 1)).0"

        sed -i -e "s/$SEMGREP_VERSION/$INCREASED_SEMGREP_VERSION/g" $FILENAME
    - name: Commit changes
      run: |
        git status
        git config --global user.name 'Security'
        git config --global user.email 'security@r2c.dev'
        git commit -m "increasing the version of historical semgrep check"
    - name: Create Pull Request
      run: |
        # TODO: `-f` in curl won't fail on all non-200 HTTP responses.
        # Instead, add a `make` command with some bash scripting in order to do this.
        curl \
        -f -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/returntocorp/semgrep-rules/pulls \
        -d '{"base":"develop","head":"up-historical-semgrep-version","title":"Increases historical semgrep version","body":"Created automatically with the Github action in increase-historical-semgrep-version.yml."}' \
