name: Increase semgrep version for historical test 
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  create-pull-request:
    if: github.repository == 'returntocorp/semgrep-rules'
    runs-on: ubuntu-latest
    steps:
    - name: Check out develop
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: develop
    - name: Create new branch
      run: |
        git checkout -b up-historical-semgrep-version
    - name: Increase version
      working-directory: .github/workflows
      shell: bash
      run: |
        echo $PWD
        ls
        FILENAME="semgrep-rules-test-historical.yml"
        SEMGREP_VERSION=`grep -ow "0.[0-9][0-9].0" $FILENAME | head -1`
        SEMGREP_VERSION_SHORT=${SEMGREP_VERSION:2:2}
        INCREASED_SEMGREP_VERSION="0.$(($SEMGREP_VERSION_SHORT + 1)).0"

        sed -i -e "s/$SEMGREP_VERSION/$INCREASED_SEMGREP_VERSION/g" $FILENAME
        # sed creates intermediary file, which we should remove
        rm "$FILENAME-e"

        echo $INCREASED_SEMGREP_VERSION
        echo $SEMGREP_VERSION
    - name: Commit changes
      run: |
        git add semgrep-rules-test-historical.yml
        git commit -m "increasing the version of historical semgrep check"
    - name: Create Pull Request
      run: |
        # TODO: `-f` in curl won't fail on all non-200 HTTP responses.
        # Instead, add a `make` command with some bash scripting in order to do this.
        curl \
        -f -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
        https://api.github.com/repos/returntocorp/semgrep-rules/pulls \
        -d '{"base":"develop","head":"up-historical-semgrep-version","title":"Increases historical semgrep version","body":"Created automatically with the Github action in increase-historical-semgrep-version.yml."}' \
