name: rule-benchmarks

on:
  workflow_dispatch:
  schedule:
  - cron: 0 0 * * MON

jobs:
  run_benchmarks:
    runs-on: ubuntu-latest
    name: Run benchmarks for each rule
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9.2
    - name: Install latest semgrep
      shell: bash
      run: |
        pip3 install semgrep
    - name: Display Semgrep version
      shell: bash
      run: |
        semgrep --version
    - name: Clone semgrep directory for perf scripts
      shell: bash
      run: |
        git clone https://github.com/returntocorp/semgrep.git
    - name: Run benchmarks
      shell: bash
      run: |
        python3 semgrep/perf/run-benchmarks --small-only --std-only --output-time-per-rule-json rule_times.json
    - name: Upload rule time JSON
      uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: rule_times.json
        path: rule_times.json
