name: semgrep-rules-pro benchmark

on:
  workflow_dispatch:
  push:
    branches: [develop, release]
  pull_request:
    branches: [develop, release]
jobs:
  trigger:
    # PRs posted by first time contributors already need approval as well
    if: github.actor != 'semgrep-dev-pr-bot'
    runs-on: ubuntu-20.04
    steps:
      - id: trigger-run
        name: Trigger semgrep-rules-pro benchmarking argo workflow on PR to develop or release
        run: |
          curl -X POST https://argo.corp.r2c.dev/api/v1/events/security-research/pro-perf-scan-test -H "Authorization: ${{ secrets.ARGO_WORKFLOWS_TOKEN }}" -d "{\"base-branch\" : \"release\", \"comparison-branch\" : \"develop\", \"rules-repository\" : \"semgrep-rules\"}"

